apiVersion: v1
kind: Pod
metadata:
  name: nfs-volume-pod
spec:
  nodeSelector:
    type: k8s-node-1
  containers:
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nfs-html
          readOnly: false
      ports:
        - containerPort: 80
          protocol: TCP
  volumes:
    - name: nfs-html
      nfs:
        server: 10.100.141.170
        path: /data/nfs
