apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc
spec:
  containers:
    - image: nginx:alpine
      name: pvc-nginx
      volumeMounts:
        - name: nginx-pvc
          mountPath: /usr/share/nginx/html
      ports:
      - containerPort: 80
        protocol: TCP
  volumes:
    - name: nginx-pvc
      persistentVolumeClaim:
        claimName: nfs-pvc

