apiVersion: v1
kind: Pod
metadata:
  name: pod-with-host-network
spec:
  hostNetwork: true
    #nodeSelector:
    #type: k8s-node-3
  containers:
  - name: main
    image: alpine
    command: ["/bin/sleep", "99999"]